### ISSUE TITLE
关于inference.py中的template_len

### ISSUE THREAD

**Issue by paizhongxing** [HLT-NLP/PromptRank#1]
请问template_len = tokenizer(temp_de, return_tensors="pt")["input_ids"].shape[1] - 3 以及for i in range(template_len, de_input_ids.shape[1] - 3)中的-3是代表什么含义呢

**Comment by pengjunfeng11** [comment]
我的猜测是为了忽略掉固定的几个special token。例如<cls>等。不过可以确定的是这个3适合一开始的prompt template有关的，如果换一个模版会不会也有可能是-6？

**Comment by pengjunfeng11** [comment]
我也有一个问题，我想问一下这个t5模型的decode_input_ids为什么可以拿来这么用，为什么t5的输出直接就是相似度了呢？兄弟你知道吗

**Comment by paizhongxing** [comment]
> 我也有一个问题，我想问一下这个t5模型的decode_input_ids为什么可以拿来这么用，为什么t5的输出直接就是相似度了呢？兄弟你知道吗

我看源代码，过程是这样的：对每一个文章和候选词，得到decoder的输出，也就是logitis，然后根据logitis矩阵中是这个候选词token的概率来得到打分，而不是相似度

**Comment by pengjunfeng11** [comment]
原来是这样！我可能对这个`decoder_input_ids`理解的不太到位，兄弟可以告诉我这个decoder_input_ids是干什么的吗，会完全参与到模型的forward计算吗？如果参与到的话，那么不相当于把最后要得到的结果通过prompt告诉t5了吗？？
烦请大哥解惑，这对我来说真的很重要😭

**Comment by pengjunfeng11** [comment]
> 

原来是这样！我可能对这个decoder_input_ids理解的不太到位，兄弟可以告诉我这个decoder_input_ids是干什么的吗，会完全参与到模型的forward计算吗？如果参与到的话，那么不相当于把最后要得到的结果通过prompt告诉t5了吗？？
烦请大哥解惑，这对我来说真的很重要😭

**Comment by pengjunfeng11** [comment]
> > 我也有一个问题，我想问一下这个t5模型的decode_input_ids为什么可以拿来这么用，为什么t5的输出直接就是相似度了呢？兄弟你知道吗
> 
> 我看源代码，过程是这样的：对每一个文章和候选词，得到decoder的输出，也就是logitis，然后根据logitis矩阵中是这个候选词token的概率来得到打分，而不是相似度

原来是这样！我可能对这个decoder_input_ids理解的不太到位，兄弟可以告诉我这个decoder_input_ids是干什么的吗，会完全参与到模型的forward计算吗？如果参与到的话，那么不相当于把最后要得到的结果通过prompt告诉t5了吗？？
烦请大哥解惑，这对我来说真的很重要😭

**Comment by paizhongxing** [comment]
> 

建议去看看T5的论文以及transformer库里面源码的相关实现,encoder-decoder模型是有decoder的输入的，decoder_input_ids作为隐藏层参与到后续的计算了

**Comment by paizhongxing** [comment]
> > > 我也有一个问题，我想问一下这个t5模型的decode_input_ids为什么可以拿来这么用，为什么t5的输出直接就是相似度了呢？兄弟你知道吗
> > 
> > 
> > 我看源代码，过程是这样的：对每一个文章和候选词，得到decoder的输出，也就是logitis，然后根据logitis矩阵中是这个候选词token的概率来得到打分，而不是相似度
> 
> 原来是这样！我可能对这个decoder_input_ids理解的不太到位，兄弟可以告诉我这个decoder_input_ids是干什么的吗，会完全参与到模型的forward计算吗？如果参与到的话，那么不相当于把最后要得到的结果通过prompt告诉t5了吗？？ 烦请大哥解惑，这对我来说真的很重要😭

建议去看看T5的论文以及transformer库里面源码的相关实现,encoder-decoder模型是有decoder的输入的，decoder_input_ids作为隐藏层参与到后续的计算了

**Comment by pengjunfeng11** [comment]
> > > > 我也有一个问题，我想问一下这个t5模型的decode_input_ids为什么可以拿来这么用，为什么t5的输出直接就是相似度了呢？兄弟你知道吗
> > > 
> > > 
> > > 我看源代码，过程是这样的：对每一个文章和候选词，得到decoder的输出，也就是logitis，然后根据logitis矩阵中是这个候选词token的概率来得到打分，而不是相似度
> > 
> > 
> > 原来是这样！我可能对这个decoder_input_ids理解的不太到位，兄弟可以告诉我这个decoder_input_ids是干什么的吗，会完全参与到模型的forward计算吗？如果参与到的话，那么不相当于把最后要得到的结果通过prompt告诉t5了吗？？ 烦请大哥解惑，这对我来说真的很重要😭
> 
> 建议去看看T5的论文以及transformer库里面源码的相关实现,encoder-decoder模型是有decoder的输入的，decoder_input_ids作为隐藏层参与到后续的计算了

好的，可能是我看的不够深入，谢谢你～！
