### ISSUE TITLE
Why t5, and how does it work

### ISSUE THREAD

**Issue by pengjunfeng11** [HLT-NLP/PromptRank#2]
I never use T5-base model before, after read yours paper, I view some blog about how to use  T5-base on the website. But I can't figure out why you can use t5 T5-base model to calculate the probability, which is the chapter 3.2 in the paper **'PromptRank: Unsupervised Keyphrase Extraction Using Prompt'**. Because to my limited knowledge, T5-base only has a few fixed prompts, and I don't know how dose it work with new prompt.
Can I know your core idea or some way to find this？Thanks! It will be very helpful to me !!

**Comment by Kong-Aobo** [comment]
Actually, I choose t5 beacause it is an encoder-decoder model. In this paper, I use encoder-decoder structure to align the document and the template filled with the candidate. And about your question, during the pretraining stage, T5 uses a few fixed prompts for multi-task training but it is essentially a language model. Don't be limited. BART also works fine for this algorithm, maybe BART is easy to understand.

**Comment by pengjunfeng11** [comment]
> Actually, I choose t5 beacause it is an encoder-decoder model. In this paper, I use encoder-decoder structure to align the document and the template filled with the candidate. And about your question, during the pretraining stage, T5 uses a few fixed prompts for multi-task training but it is essentially a language model. Don't be limited. BART also works fine for this algorithm, maybe BART is easy to understand.

Thanks!! it will help me a lot!
