### ISSUE TITLE
关于复现结果

### ISSUE THREAD

**Issue by lpc2000-begin** [HLT-NLP/PromptRank#4]
您好，在对论文结果进行复现的过程中，我发现对于Inspec和SemEval2017两个短文本数据集上的结果与论文数据差距过大，有的甚至达到了5个点左右，而对于另外四个较长文本数据集结果与论文数据较为接近。
以下是我的result.txt的输出
max_len: 512
temp_en: Book:
temp_de: This book mainly talks about 
model: base
enable_filter: False
enable_pos: True
position_factor: 120000000.0
length_factor: 0.6
Inspec
0.29087965461413917
0.33792544570502436
0.3372131147540984
SemEval2017
0.2527921547262326
0.3433953867833568
0.3767007335883128
SemEval2010
0.1634280019930244
0.19625049860390906
0.2008646491519787
DUC2001
0.26643426294820716
0.3017847485127096
0.2992349107395863
krapivin
0.1554341226472374
0.1632371219444828
0.15281417042238757
nus
0.17178612059158133
0.19820608182017063
0.20014219694276572

0.2167923862534037
0.2567998805616089
0.2611616292665216

**Comment by Kong-Aobo** [comment]
您好，您检查一下是否修改了代码，各种包的版本等是否与 README 中的一致，以及脚本的执行是否有误。我这边 Inspec 和 SemEval2017 的结果文件的最后如下：
```
Inspec
N=5
P=0.4704
R=0.23941368078175895
F1=0.31732325957906093


N=10
P=0.3771947527749748
R=0.38049674267100975
F1=0.37883855275159617


N=15
P=0.3202262693156733
R=0.47251628664495116
F1=0.3817434210526316

max_len: 512
temp_en: Book:
temp_de: This book mainly talks about
model: base
enable_filter: False
enable_pos: True
position_factor: 120000000.0
length_factor: 0.6
Processing time: 221.1300024986267
```
```
SemEval2017 
N=5
P=0.605668016194332
R=0.17511412852627883
F1=0.2716789249069282


N=10
P=0.5153846153846153
R=0.29802177221116705
F1=0.37766075799154486


N=15
P=0.44765635553154126
R=0.3879199344492567
F1=0.4156528282954974

max_len: 512
temp_en: Book:
temp_de: This book mainly talks about
model: base
enable_filter: False
enable_pos: True
position_factor: 120000000.0
length_factor: 0.6
Processing time: 259.0336158275604
```

**Comment by lpc2000-begin** [comment]
感谢您的耐心回复，将原来的StanfordCoreNLP版本替换为StanfordCoreNLP 3.9.1.1后得到了和论文数据相匹配的结果
