### ISSUE TITLE
Excuse me, does this support Chinese?

### ISSUE THREAD

**Issue by zdaiot** [HLT-NLP/PromptRank#6]

**Comment by Kong-Aobo** [comment]
No. You can modify the current code relatively simply to make it compatible with Chinese. I have already attempted modifications and demonstrated the effectiveness of the method on a partial Chinese dataset. Note that you will need to replace the pre-trained model and prompt. For certain reasons, I cannot open-source the code supporting Chinese.

**Comment by zdaiot** [comment]
Thanks a lot, I also want to ask.

1、In the POS Tagger step, in addition to changing `en_model = StanfordCoreNLP (StanfordCoreNLP_path, quiet=True)` to `en_model = StanfordCoreNLP (StanfordCoreNLP_path, lang='zh', quiet=True)`. And changing stopword_dict to chinese stopword_dict. Is there anything else that needs to be changed? 

2、In addition, why don't you use the latest version of StanfordCoreNLP? But use 2018-02-27?

3、Finally, which Chinese Pretrain-model do you use?

Thanks again

**Comment by Kong-Aobo** [comment]
I answer your second question. I just follow previous work to use 2018-02-27 so that I can use their code directly. You can try the latest version but all hyperparameters may need to be modified.

**Comment by zdaiot** [comment]
Thanks a lot
